POST http://localhost:1889/videos
Content-Type: application/json

{
  "title": "Título do video",
  "description": "Descrição do video",
  "duration": 180
}

###

GET http://localhost:1889/videos

###

PUT http://localhost:1889/videos/4dfc2569-1ee8-4cd7-9256-446e7efa95e0
Content-Type: application/json

{
  "title": "Título Novo do video caraii",
  "description": "Descrição Nova do video",
  "duration": 190
}

###

DELETE http://localhost:1889/videos/4dfc2569-1ee8-4cd7-9256-446e7efa95e0

###